# -*- mode: ruby -*-
# vi: set ft=ruby :


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # please see the online documentation at vagrantup.com.
  # VAGRANT WINDOWS:  https://github.com/WinRb/vagrant-windows


  # Every Vagrant virtual environment requires a box to build off of.
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 712
  end

  config.vm.define "linuxdev" do |linuxdev|
      linuxdev.vm.box = "trusty64"
      linuxdev.vm.provision :shell, :path => "./bootstrap.sh"

      # The url from where the 'config.vm.box' box will be fetched if it
      # doesn't already exist on the user's system.
      linuxdev.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
      
      linuxdev.vm.network "private_network", ip: "192.168.66.4"
    

  end

end